import type { EngineInterface, Register } from 'claude-code'
import { agents, catalogText, findAgent, invocation } from './catalog.ts'
import { initialState, reconcile, recordResult, resultDraft, resultStatus, statusLabel } from './state.ts'

let state = initialState()
let filling = false

async function refresh($: EngineInterface) {
  try {
    state = reconcile(state, await $.agent.list())
  } catch {
    state = { ...state, statusError: 'Native status is unavailable. No job state inferred.' }
  }
}

async function fill($: EngineInterface, text: string) {
  if (filling) return 'A draft action is already in progress.'
  filling = true
  try {
    const result = await $.prompt.fill({ text, mode: 'replace' })
    return result.isFilled
      ? 'Selected for next task. Review the visible draft and press Enter to invoke the native agent.'
      : 'Claude could not fill the draft here. Nothing started. Use this in an interactive session.'
  } finally {
    filling = false
  }
}

// Source: official Mods create/test docs and declarations generated by 2.1.287.
// No model/agent spawn, prompt submission, permission, tool or auth interception.
export const register: Register = on => {
  on('session.start', async ($, e, next) => {
    await $.command.register({
      name: 'kit',
      description: 'Browse Kit specialists, prepare a visible task draft, or inspect this session',
      argumentHint: '[catalog | use <bucket> | jobs | review <result> | handoff <result> <bucket>]',
      immediate: true,
    })
    return next(e)
  })

  on('command.run', { command: 'kit' }, async ($, e) => {
    const [action = 'catalog', target = '', bucket = ''] = e.args.trim().split(/\s+/).filter(Boolean)
    if (action === 'catalog') {
      return { text: `${catalogText()}\n\nSelected for next task: ${state.selected}\n/kit use <bucket> prepares a visible draft. Nothing starts until you send it.` }
    }
    if (action === 'use') {
      const agent = findAgent(target)
      if (!agent) return { text: 'Choose Frontend, Backend, Security or Product.' }
      const draft = await $.prompt.read()
      const text = await fill($, invocation(agent, draft.text))
      // Selection describes intent only, never a running task.
      state = { ...state, selected: agent.id }
      return { text }
    }
    if (action === 'jobs') {
      await refresh($)
      if (state.statusError) return { text: state.statusError }
      const rows = state.jobs.map(j => `${j.id} · ${j.type} · ${statusLabel(j.status)}\n  ${j.description}`)
      const results = state.results.filter(r => state.jobs.some(j => j.id === r.agentId))
        .map(r => `${r.key} · ${resultStatus(r.reason)}`)
      return { text: ['This Claude session only.', ...rows,
        ...(rows.length ? [] : ['No Kit jobs observed.']),
        ...results.map(r => `Result: ${r}`)].join('\n') }
    }
    if (action === 'review' || action === 'handoff') {
      const result = state.results.find(r => r.key === target)
      if (!result) return { text: 'No captured result with that exact key. Run /kit jobs; results from before this mod loaded are unavailable.' }
      const agent = action === 'review' ? findAgent('Security') : findAgent(bucket)
      if (!agent) return { text: 'Choose the receiving bucket after the result key.' }
      const draft = await $.prompt.read()
      if (draft.text.trim()) return { text: 'Your draft contains text. Send or clear it before preparing a result handoff.' }
      return { text: await fill($, resultDraft(result, agent, action)) }
    }
    return { text: 'Use /kit catalog, /kit use <bucket>, /kit jobs, /kit review <result>, or /kit handoff <result> <bucket>.' }
  })

  on('turn.complete', async ($, e, next) => {
    const result = await next(e)
    if (e.agentId) {
      await refresh($)
      const job = !state.statusError && state.jobs.find(j => j.id === e.agentId && j.status !== 'not-attached')
      if (job && agents.some(a => a.id === job.type)) {
        state = recordResult(state, {
          agentId: e.agentId, agentType: job.type, task: job.description,
          turnId: e.turnId, answer: e.answer, reason: e.reason,
        })
      }
    }
    return result
  })
}
